version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tajir_pro_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tajir_pro
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tajir
      MYSQL_PASSWORD: tajir123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tajir_pro_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data: 